[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "grlg-geo"
version = "0.1.0"
description = "Ultra-fast zero-copy binary GeoIP and Proxy/VPN threat database compiler and reader"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
authors = [
    { name = "ulquiorracode", email = "ulquiorracode@users.noreply.github.com" }
]
keywords = ["geoip", "proxy", "vpn", "threat-intelligence", "binary-format", "mmap", "networking"]
classifiers = [
    "Topic :: Internet",
    "Topic :: Security",
    "Topic :: System :: Networking",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License"
]
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
grlg = "grlg.cli:main"

[tool.setuptools]
packages = ["grlg"]
